services:
  orders-api:
    build:
      context: ./src/Orders.API
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - api-gateway-net

  products-api:
    build:
      context: ./src/Products.API
      dockerfile: Dockerfile
    ports:
      - "6000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - api-gateway-net

  krakend:
    image: devopsfaith/krakend:watch
    volumes:
      - ${PWD}/config/krakend:/etc/krakend:ro
    ports:
      - "1234:1234"
      - "8080:8080"
      - "8090:8090"
    command: ["run", "-c", "/etc/krakend/krakend.json", "-d"]
    networks:
      - api-gateway-net

networks:
  api-gateway-net:
    driver: bridge
